name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: install poetry
      uses: Gr1N/setup-poetry@v7

    - name: install dependencies
      run: poetry install

    - name: Tests
      run: poetry run coverage run -m pytest && poetry run coverage xml

    - name: Lint
      run: poetry run flake8

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
